/* 
 * Copyright (C) 2015 Sean T. McBeth <sean@seanmcbeth.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

CodePages.EN_UKX = {
    name: "English: UK Extended",
    language: "en-GB",
    CTRLALT: {
        "52": "€",
        "65": "á",
        "69": "é",
        "73": "í",
        "79": "ó",
        "85": "ú",
        "163": "\\",
        "192": "¦",
        "222": "\\",
        "223": "¦"
    },
    CTRLALTSHIFT: {
        "65": "Á",
        "69": "É",
        "73": "Í",
        "79": "Ó",
        "85": "Ú",
        "222": "|"
    },
    NORMAL: {
        "32": " ",
        "48": "0",
        "49": "1",
        "50": "2",
        "51": "3",
        "52": "4",
        "53": "5",
        "54": "6",
        "55": "7",
        "56": "8",
        "57": "9",
        "59": ";",
        "61": "=",
        "65": "a",
        "66": "b",
        "67": "c",
        "68": "d",
        "69": "e",
        "70": "f",
        "71": "g",
        "72": "h",
        "73": "i",
        "74": "j",
        "75": "k",
        "76": "l",
        "77": "m",
        "78": "n",
        "79": "o",
        "80": "p",
        "81": "q",
        "82": "r",
        "83": "s",
        "84": "t",
        "85": "u",
        "86": "v",
        "87": "w",
        "88": "x",
        "89": "y",
        "90": "z",
        "163": "#",
        "173": "-",
        "186": ";",
        "187": "=",
        "188": ",",
        "189": "-",
        "190": ".",
        "191": "/",
        "192": "'",
        "219": "[",
        "220": "\\",
        "221": "]",
        "222": "#",
        "223": "`"
    },
    SHIFT: {
        "32": " ",
        "48": ")",
        "49": "!",
        "50": "\"",
        "51": "£",
        "52": "$",
        "53": "%",
        "54": "^",
        "55": "&",
        "56": "*",
        "57": "(",
        "59": ":",
        "61": "+",
        "65": "A",
        "66": "B",
        "67": "C",
        "68": "D",
        "69": "E",
        "70": "F",
        "71": "G",
        "72": "H",
        "73": "I",
        "74": "J",
        "75": "K",
        "76": "L",
        "77": "M",
        "78": "N",
        "79": "O",
        "80": "P",
        "81": "Q",
        "82": "R",
        "83": "S",
        "84": "T",
        "85": "U",
        "86": "V",
        "87": "W",
        "88": "X",
        "89": "Y",
        "90": "Z",
        "163": "~",
        "173": "_",
        "186": ":",
        "187": "+",
        "188": "<",
        "189": "_",
        "190": ">",
        "191": "?",
        "192": "@",
        "219": "{",
        "220": "|",
        "221": "}",
        "222": "~",
        "223": "¬"
    }
};