/* 
 * Copyright (C) 2015 Sean T. McBeth <sean@seanmcbeth.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

// eventually, this will have configurable values for different locales.

var Keys = {};
Keys.BACKSPACE = 8;
Keys.TAB = 9;
Keys.ENTER = 13;
Keys.SHIFT = 16;
Keys.CTRL = 17;
Keys.ALT = 18;
Keys.PAUSEBREAK = 19;
Keys.CAPSLOCK = 20;
Keys.ESCAPE = 27;
Keys.SPACEBAR = 32;
Keys.PAGEUP = 33;
Keys.PAGEDOWN = 34;
Keys.END = 35;
Keys.HOME = 36;
Keys.LEFTARROW = 37;
Keys.UPARROW = 38;
Keys.RIGHTARROW = 39;
Keys.DOWNARROW = 40;
Keys.INSERT = 45;
Keys.DELETE = 46;
Keys.NUMBER0 = 48;
Keys.NUMBER1 = 49;
Keys.NUMBER2 = 50;
Keys.NUMBER3 = 51;
Keys.NUMBER4 = 52;
Keys.NUMBER5 = 53;
Keys.NUMBER6 = 54;
Keys.NUMBER7 = 55;
Keys.NUMBER8 = 56;
Keys.NUMBER9 = 57;
Keys.A = 65;
Keys.B = 66;
Keys.C = 67;
Keys.D = 68;
Keys.E = 69;
Keys.F = 70;
Keys.G = 71;
Keys.H = 72;
Keys.I = 73;
Keys.J = 74;
Keys.K = 75;
Keys.L = 76;
Keys.M = 77;
Keys.N = 78;
Keys.O = 79;
Keys.P = 80;
Keys.Q = 81;
Keys.R = 82;
Keys.S = 83;
Keys.T = 84;
Keys.U = 85;
Keys.V = 86;
Keys.W = 87;
Keys.X = 88;
Keys.Y = 89;
Keys.Z = 90;
Keys.LEFTWINDOWKEY = 91;
Keys.RIGHTWINDOWKEY = 92;
Keys.SELECTKEY = 93;
Keys.NUMPAD0 = 96;
Keys.NUMPAD1 = 97;
Keys.NUMPAD2 = 98;
Keys.NUMPAD3 = 99;
Keys.NUMPAD4 = 100;
Keys.NUMPAD5 = 101;
Keys.NUMPAD6 = 102;
Keys.NUMPAD7 = 103;
Keys.NUMPAD8 = 104;
Keys.NUMPAD9 = 105;
Keys.MULTIPLY = 106;
Keys.ADD = 107;
Keys.SUBTRACT = 109;
Keys.DECIMALPOINT = 110;
Keys.DIVIDE = 111;
Keys.F1 = 112;
Keys.F2 = 113;
Keys.F3 = 114;
Keys.F4 = 115;
Keys.F5 = 116;
Keys.F6 = 117;
Keys.F7 = 118;
Keys.F8 = 119;
Keys.F9 = 120;
Keys.F10 = 121;
Keys.F11 = 122;
Keys.F12 = 123;
Keys.NUMLOCK = 144;
Keys.SCROLLLOCK = 145;
Keys.SEMICOLON = 186;
Keys.EQUALSIGN = 187;
Keys.COMMA = 188;
Keys.DASH = 189;
Keys.PERIOD = 190;
Keys.FORWARDSLASH = 191;
Keys.GRAVEACCENT = 192;
Keys.OPENBRACKET = 219;
Keys.BACKSLASH = 220;
Keys.CLOSEBRACKET = 221;
Keys.SINGLEQUOTE = 222;

CodePages = {};

CodePages.EN_US = {LOWERCASE: {}, UPPERCASE: {}};
CodePages.EN_US.LOWERCASE[Keys.A] = "a";
CodePages.EN_US.LOWERCASE[Keys.B] = "b";
CodePages.EN_US.LOWERCASE[Keys.C] = "c";
CodePages.EN_US.LOWERCASE[Keys.D] = "d"; 
CodePages.EN_US.LOWERCASE[Keys.E] = "e";
CodePages.EN_US.LOWERCASE[Keys.F] = "f";
CodePages.EN_US.LOWERCASE[Keys.G] = "g";
CodePages.EN_US.LOWERCASE[Keys.H] = "h";
CodePages.EN_US.LOWERCASE[Keys.I] = "i";
CodePages.EN_US.LOWERCASE[Keys.J] = "j";
CodePages.EN_US.LOWERCASE[Keys.K] = "k";
CodePages.EN_US.LOWERCASE[Keys.L] = "l";
CodePages.EN_US.LOWERCASE[Keys.M] = "m";
CodePages.EN_US.LOWERCASE[Keys.N] = "n";
CodePages.EN_US.LOWERCASE[Keys.O] = "o";
CodePages.EN_US.LOWERCASE[Keys.P] = "p";
CodePages.EN_US.LOWERCASE[Keys.Q] = "q";
CodePages.EN_US.LOWERCASE[Keys.R] = "r";
CodePages.EN_US.LOWERCASE[Keys.S] = "s";
CodePages.EN_US.LOWERCASE[Keys.T] = "t";
CodePages.EN_US.LOWERCASE[Keys.U] = "u";
CodePages.EN_US.LOWERCASE[Keys.V] = "v";
CodePages.EN_US.LOWERCASE[Keys.W] = "w";
CodePages.EN_US.LOWERCASE[Keys.X] = "x";
CodePages.EN_US.LOWERCASE[Keys.Y] = "y";
CodePages.EN_US.LOWERCASE[Keys.Z] = "z";
CodePages.EN_US.LOWERCASE[Keys.SPACEBAR] = " ";
CodePages.EN_US.LOWERCASE[Keys.NUMBER0] = "0";
CodePages.EN_US.LOWERCASE[Keys.NUMBER1] = "1";
CodePages.EN_US.LOWERCASE[Keys.NUMBER2] = "2";
CodePages.EN_US.LOWERCASE[Keys.NUMBER3] = "3";
CodePages.EN_US.LOWERCASE[Keys.NUMBER4] = "4";
CodePages.EN_US.LOWERCASE[Keys.NUMBER5] = "5";
CodePages.EN_US.LOWERCASE[Keys.NUMBER6] = "6";
CodePages.EN_US.LOWERCASE[Keys.NUMBER7] = "7";
CodePages.EN_US.LOWERCASE[Keys.NUMBER8] = "8";
CodePages.EN_US.LOWERCASE[Keys.NUMBER9] = "9";
CodePages.EN_US.LOWERCASE[Keys.MULTIPLY] = "*";
CodePages.EN_US.LOWERCASE[Keys.ADD] = "+";
CodePages.EN_US.LOWERCASE[Keys.SUBTRACT] = "-";
CodePages.EN_US.LOWERCASE[Keys.DECIMALPOINT] = ".";
CodePages.EN_US.LOWERCASE[Keys.DIVIDE] = "/";
CodePages.EN_US.LOWERCASE[Keys.SEMICOLON] = ";";
CodePages.EN_US.LOWERCASE[Keys.EQUALSIGN] = "=";
CodePages.EN_US.LOWERCASE[Keys.COMMA] = ",";
CodePages.EN_US.LOWERCASE[Keys.DASH] = "-";
CodePages.EN_US.LOWERCASE[Keys.PERIOD] = ".";
CodePages.EN_US.LOWERCASE[Keys.FORWARDSLASH] = "/";
CodePages.EN_US.LOWERCASE[Keys.GRAVEACCENT] = "`";
CodePages.EN_US.LOWERCASE[Keys.OPENBRACKET] = "[";
CodePages.EN_US.LOWERCASE[Keys.BACKSLASH] = "\\";
CodePages.EN_US.LOWERCASE[Keys.CLOSEBRACKET] = "]";
CodePages.EN_US.LOWERCASE[Keys.SINGLEQUOTE] = "'";

CodePages.EN_US.UPPERCASE[Keys.A] = "A";
CodePages.EN_US.UPPERCASE[Keys.B] = "B";
CodePages.EN_US.UPPERCASE[Keys.C] = "C";
CodePages.EN_US.UPPERCASE[Keys.D] = "D";
CodePages.EN_US.UPPERCASE[Keys.E] = "E";
CodePages.EN_US.UPPERCASE[Keys.F] = "F";
CodePages.EN_US.UPPERCASE[Keys.G] = "G";
CodePages.EN_US.UPPERCASE[Keys.H] = "H";
CodePages.EN_US.UPPERCASE[Keys.I] = "I";
CodePages.EN_US.UPPERCASE[Keys.J] = "J";
CodePages.EN_US.UPPERCASE[Keys.K] = "K";
CodePages.EN_US.UPPERCASE[Keys.L] = "L";
CodePages.EN_US.UPPERCASE[Keys.M] = "M";
CodePages.EN_US.UPPERCASE[Keys.N] = "N";
CodePages.EN_US.UPPERCASE[Keys.O] = "O";
CodePages.EN_US.UPPERCASE[Keys.P] = "P";
CodePages.EN_US.UPPERCASE[Keys.Q] = "Q";
CodePages.EN_US.UPPERCASE[Keys.R] = "R";
CodePages.EN_US.UPPERCASE[Keys.S] = "S";
CodePages.EN_US.UPPERCASE[Keys.T] = "T";
CodePages.EN_US.UPPERCASE[Keys.U] = "U";
CodePages.EN_US.UPPERCASE[Keys.V] = "V";
CodePages.EN_US.UPPERCASE[Keys.W] = "W";
CodePages.EN_US.UPPERCASE[Keys.X] = "X";
CodePages.EN_US.UPPERCASE[Keys.Y] = "Y";
CodePages.EN_US.UPPERCASE[Keys.Z] = "Z";
CodePages.EN_US.UPPERCASE[Keys.SPACEBAR] = " ";
CodePages.EN_US.UPPERCASE[Keys.NUMBER0] = ")";
CodePages.EN_US.UPPERCASE[Keys.NUMBER1] = "!";
CodePages.EN_US.UPPERCASE[Keys.NUMBER2] = "@";
CodePages.EN_US.UPPERCASE[Keys.NUMBER3] = "#";
CodePages.EN_US.UPPERCASE[Keys.NUMBER4] = "$";
CodePages.EN_US.UPPERCASE[Keys.NUMBER5] = "%";
CodePages.EN_US.UPPERCASE[Keys.NUMBER6] = "^";
CodePages.EN_US.UPPERCASE[Keys.NUMBER7] = "&";
CodePages.EN_US.UPPERCASE[Keys.NUMBER8] = "*";
CodePages.EN_US.UPPERCASE[Keys.NUMBER9] = "(";
CodePages.EN_US.UPPERCASE[Keys.MULTIPLY] = "*";
CodePages.EN_US.UPPERCASE[Keys.ADD] = "+";
CodePages.EN_US.UPPERCASE[Keys.SUBTRACT] = "-";
CodePages.EN_US.UPPERCASE[Keys.DECIMALPOINT] = ".";
CodePages.EN_US.UPPERCASE[Keys.DIVIDE] = "/";
CodePages.EN_US.UPPERCASE[Keys.SEMICOLON] = ":";
CodePages.EN_US.UPPERCASE[Keys.EQUALSIGN] = "+";
CodePages.EN_US.UPPERCASE[Keys.COMMA] = "<";
CodePages.EN_US.UPPERCASE[Keys.DASH] = "_";
CodePages.EN_US.UPPERCASE[Keys.PERIOD] = ">";
CodePages.EN_US.UPPERCASE[Keys.FORWARDSLASH] = "?";
CodePages.EN_US.UPPERCASE[Keys.GRAVEACCENT] = "~";
CodePages.EN_US.UPPERCASE[Keys.OPENBRACKET] = "{";
CodePages.EN_US.UPPERCASE[Keys.BACKSLASH] = "|";
CodePages.EN_US.UPPERCASE[Keys.CLOSEBRACKET] = "}";
CodePages.EN_US.UPPERCASE[Keys.SINGLEQUOTE] = "\"";
